- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: velociraptor
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/astrawinski/ansible_desktop.git"
