- name: install packages
  package:
    name:
      - htop
      - tmux
      - python3-psutil
      - open-vm-tools
      - open-vm-tools-desktop
      - openssh-server

- name: copy wallpaper file
  copy:
    src: files/wallpaper.jpeg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root

- name: set wallpaper
  become_user: astrawinski
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: set wallpaper position
  become_user: astrawinski
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: copy .bashrc file
  copy:
    src: files/bashrc
    dest: /home/astrawinski/.bashrc
    owner: astrawinski
    group: astrawinski
